export const metadata = {
  title: "Terms of Service — d3ftly",
};

export default function Terms() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p><strong>Effective date:</strong> July 14, 2025</p>

      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of the d3ftly website and GitHub
        App (the &quot;Service&quot;) operated by d3ftly (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;).
        By installing the GitHub App or accessing the Service, you agree to these Terms.
      </p>

      <h2>1. Eligibility</h2>
      <p>You must be at least 16 years old and have the authority to bind the organization
        (if applicable) to use this Service. By installing the GitHub App on an organization,
        you represent that you have the necessary permissions.</p>

      <h2>2. Description of Service</h2>
      <p>d3ftly is an autonomous AI coding agent delivered as a GitHub App. It reads issues
        assigned to it, analyzes your codebase, generates code changes, and opens pull requests.
        The Service is provided on an &quot;as is&quot; and &quot;as available&quot; basis.</p>

      <h2>3. Your Responsibilities</h2>
      <ul>
        <li>You are responsible for reviewing all code changes made by d3ftly before merging.</li>
        <li>You must not use the Service to generate malicious code, malware, or code that
          violates any law or third-party rights.</li>
        <li>You must comply with GitHub&apos;s Terms of Service and Acceptable Use Policies.</li>
        <li>You are responsible for any consequences of merging d3ftly-generated code into
          your repositories.</li>
      </ul>

      <h2>4. Intellectual Property</h2>
      <p>Code generated by d3ftly for your repositories belongs to you. We claim no ownership
        of your code, repositories, or the output produced by the Service. The Service itself,
        including its name, brand, and underlying technology, remains our intellectual property.</p>

      <h2>5. Pricing and Payment</h2>
      <p>The free tier includes a limited number of runs per month. Paid plans are billed
        monthly via Stripe. Prices may change with 30 days&apos; notice. You may cancel your
        subscription at any time; access continues until the end of the billing period.</p>

      <h2>6. Limitation of Liability</h2>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, d3ftly SHALL NOT BE LIABLE FOR ANY INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS,
        DATA, OR GOODWILL, ARISING OUT OF YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY SHALL
        NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM.</p>

      <h2>7. Disclaimer of Warranties</h2>
      <p>THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
        IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE CODE GENERATED BY THE SERVICE WILL BE
        ERROR-FREE, SECURE, OR SUITABLE FOR ANY PURPOSE.</p>

      <h2>8. Indemnification</h2>
      <p>You agree to indemnify and hold harmless d3ftly from any claims, damages, or expenses
        arising from your use of the Service, including any code merged into your repositories.</p>

      <h2>9. Termination</h2>
      <p>We may suspend or terminate your access to the Service at any time for violation of
        these Terms or for any other reason with reasonable notice. You may terminate by
        uninstalling the GitHub App at any time.</p>

      <h2>10. Governing Law</h2>
      <p>These Terms are governed by the laws of the State of New York, without regard to
        conflict of law provisions.</p>

      <h2>11. Changes to Terms</h2>
      <p>We may modify these Terms at any time. Material changes will be communicated via the
        Service or by email. Continued use after changes constitutes acceptance.</p>

      <h2>12. Contact</h2>
      <p>Questions about these Terms? Contact us at{" "}
        <a href="mailto:legal@d3ftly.com">legal@d3ftly.com</a>.
      </p>
    </>
  );
}
